
# AWS Events Cognito Info
COGNITO_POOL_ID   = "us-east-1_Xuc1O0biz"
COGNITO_CLIENT_ID = "2h40eam2atft40g0c3mlg0aei1"

# AWS Events Portal Secrets
AWS_EVENTS_USERNAME = 'AWS_EVENTS_USERNAME'
AWS_EVENTS_PASSWORD = 'AWS_EVENTS_PASSWORD'
